server.port=8082
spring.application.name=vehicle-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/vehicle_db
spring.datasource.username=postgres
spring.datasource.password=Ayush@123
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Security Secret (Must match User Service secret)
app.jwt.secret=MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNA==
# This will log EVERY filter Spring Security uses
logging.level.org.springframework.security=DEBUG