server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.instance.prefer-ip-address=true

# Simple Route Mapping
spring.cloud.gateway.routes[0].id=user-service-route
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.routes[1].id=vehicle-service-route
spring.cloud.gateway.routes[1].uri=lb://VEHICLE-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/vehicles/**

# Add this for the Booking Service
spring.cloud.gateway.routes[2].id=booking-service-route
spring.cloud.gateway.routes[2].uri=lb://BOOKING-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/bookings/**

spring.cloud.gateway.routes[2].filters[0]=PreserveHostHeader

# This allows the Gateway to match 'vehicle-service' to 'VEHICLE-SERVICE'
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.discovery.locator.enabled=true

# Also add this to ensure the Gateway can "see" the IP
eureka.instance.instance-id=${spring.application.name}:${random.value}

# ? CORS CONFIG (FINAL)
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true


